
all:
	cd Fonts; make
	cd Postscript; make
	cd XGrafik; make

install:
	cd Fonts; make install
	cd Postscript; make install
	cd XGrafik; make install

clean:
	cd Fonts; make clean
	cd Postscript; make clean
	cd XGrafik; make clean

